export type Stop = {
  id: string;
  name: string;
  place: string;
  country: string;
  code: string;
  coords: [number, number];
  milk: string;
  texture: string;
  description: string;
  bread: string;
  wine: string;
  tea: string;
  coffee: string;
  venue?: string;
  source?: string;
  visitNote?: string;
  label?: [number, number];
};

export const stops: Stop[] = [
  {
    id: "cheddar",
    name: "Cheddar",
    place: "Cheddar, Somerset",
    country: "United Kingdom",
    code: "GB",
    coords: [-2.776, 51.279],
    milk: "Cow",
    texture: "Firm & crumbly",
    description:
      "Start where the name began. A proper farmhouse cheddar is grassy, savoury, and full of little surprises — best enjoyed slowly, with a view of the gorge.",
    bread: "Oatcakes",
    wine: "Dry Somerset cider",
    tea: "Assam black tea",
    coffee: "Medium-roast filter coffee",
    venue: "Cheddar Gorge Cheese Company",
    source: "https://www.cheddargorgecheese.com/",
    label: [-64, -14],
  },
  {
    id: "stilton",
    name: "Stilton",
    place: "Melton Mowbray, Leicestershire",
    country: "United Kingdom",
    code: "GB",
    coords: [-0.887, 52.765],
    milk: "Cow",
    texture: "Rich & blue",
    description:
      "A blue with a generous heart: creamy at first, then wonderfully savoury. Explore the cheesemongers of Leicestershire and take a wedge home for the evening.",
    bread: "Walnut bread",
    wine: "Tawny port",
    tea: "Keemun black tea",
    coffee: "Chocolate-toned espresso",
  },
  {
    id: "wensleydale",
    name: "Wensleydale",
    place: "Hawes, Yorkshire",
    country: "United Kingdom",
    code: "GB",
    coords: [-2.197, 54.304],
    milk: "Cow",
    texture: "Fresh & crumbly",
    description:
      "A milky, gently tart cheese for a picnic in the Yorkshire Dales. Keep the plate simple and leave plenty of room for the landscape.",
    bread: "Fruit loaf",
    wine: "Dry apple cider",
    tea: "Yorkshire black tea",
    coffee: "Light-roast filter coffee",
  },
  {
    id: "edam",
    name: "Edam",
    place: "Edam, North Holland",
    country: "Netherlands",
    code: "NL",
    coords: [5.049, 52.513],
    milk: "Cow",
    texture: "Mellow & smooth",
    description:
      "Canals, narrow streets, and a cheese made for travelling. Look for an aged Edam to discover its deeper, nutty side.",
    bread: "Rye crispbread",
    wine: "Pinot gris",
    tea: "Roasted oolong",
    coffee: "Gentle cold brew",
  },
  {
    id: "gouda",
    name: "Gouda",
    place: "Gouda, South Holland",
    country: "Netherlands",
    code: "NL",
    coords: [4.711, 52.012],
    milk: "Cow",
    texture: "Nutty & crystalline",
    description:
      "Aged Gouda is a small lesson in patience: caramel notes, a deep savoury finish, and those delightful crystals. Try a young wheel alongside an older one.",
    bread: "Seeded crackers",
    wine: "Chenin blanc",
    tea: "Hojicha",
    coffee: "Caramel-toned espresso",
    label: [16, -5],
  },
  {
    id: "camembert",
    name: "Camembert",
    place: "Camembert, Normandy",
    country: "France",
    code: "FR",
    coords: [0.177, 48.893],
    milk: "Cow",
    texture: "Soft & earthy",
    description:
      "Normandy in a little wooden box. Let a ripe Camembert warm up before tasting, then add crusty bread and something bright in your glass.",
    bread: "Crusty baguette",
    wine: "Normandy cider",
    tea: "Darjeeling",
    coffee: "Light-roast pour-over",
    label: [-87, -8],
  },
  {
    id: "brie",
    name: "Brie de Meaux",
    place: "Meaux, Île-de-France",
    country: "France",
    code: "FR",
    coords: [2.895, 48.96],
    milk: "Cow",
    texture: "Soft & buttery",
    description:
      "Under its pale rind, Brie de Meaux is all butter, mushrooms, and quiet richness. A fine excuse to linger over lunch east of Paris.",
    bread: "Pain de campagne",
    wine: "Brut Champagne",
    tea: "White peony tea",
    coffee: "Mellow filter coffee",
  },
  {
    id: "comte",
    name: "Comté",
    place: "Poligny, Jura",
    country: "France",
    code: "FR",
    coords: [5.708, 46.837],
    milk: "Cow",
    texture: "Firm & nutty",
    description:
      "Meet the Jura through its most delicious tradition. Each wheel tells a slightly different story of meadow, season, and time in the cellar.",
    bread: "Walnut sourdough",
    wine: "Jura Chardonnay",
    tea: "Roasted oolong",
    coffee: "Nutty medium roast",
    venue: "La Maison du Comté",
    source: "https://www.maison-du-comte.com/",
    visitNote:
      "A visitor centre and tasting experience; consult the Comté directory for working dairies.",
    label: [-65, -5],
  },
  {
    id: "emmental",
    name: "Emmentaler",
    place: "Affoltern im Emmental",
    country: "Switzerland",
    code: "CH",
    coords: [7.734, 47.064],
    milk: "Cow",
    texture: "Supple & sweet",
    description:
      "Rolling green hills and the world’s most recognisable holes. Behind the familiar shape is a gentle, rounded cheese with a lovely hazelnut finish.",
    bread: "Dark rye bread",
    wine: "Swiss Pinot blanc",
    tea: "Genmaicha",
    coffee: "Medium-roast filter coffee",
    venue: "Emmentaler Show Dairy",
    source:
      "https://www.emmentaler.ch/en/interactive-experiences/emmentaler-show-dairy",
  },
  {
    id: "gruyere",
    name: "Le Gruyère AOP",
    place: "Gruyères, Fribourg",
    country: "Switzerland",
    code: "CH",
    coords: [7.072, 46.582],
    milk: "Cow",
    texture: "Firm & nutty",
    description:
      "Alpine meadows. Copper vats. Centuries of patience. A nutty, deeply savoury cheese that tastes even better where its story began.",
    bread: "Rustic sourdough",
    wine: "Chasselas",
    tea: "Roasted oolong",
    coffee: "Hazelnut-toned filter coffee",
    venue: "La Maison du Gruyère",
    source: "https://www.lamaisondugruyere.ch/homepage-en/",
    label: [21, 28],
  },
  {
    id: "reblochon",
    name: "Reblochon",
    place: "Thônes, Haute-Savoie",
    country: "France",
    code: "FR",
    coords: [6.325, 45.882],
    milk: "Cow",
    texture: "Soft & creamy",
    description:
      "A mountain cheese with a soft centre and a gentle earthy rind. Take it to a sunny terrace, break some bread, and let the afternoon unfold.",
    bread: "Country sourdough",
    wine: "Savoie Apremont",
    tea: "Darjeeling",
    coffee: "Gentle cold brew",
  },
  {
    id: "allgau",
    name: "Allgäuer Bergkäse",
    place: "Oberstdorf, Allgäu",
    country: "Germany",
    code: "DE",
    coords: [10.279, 47.408],
    milk: "Cow",
    texture: "Firm & savoury",
    description:
      "A taste of high pastures in the Bavarian Alps. Aged mountain cheese brings a long, savoury finish to a very simple supper.",
    bread: "Bavarian rye",
    wine: "Dry Riesling",
    tea: "Hojicha",
    coffee: "Medium-roast filter coffee",
  },
  {
    id: "gorgonzola",
    name: "Gorgonzola",
    place: "Gorgonzola, Lombardy",
    country: "Italy",
    code: "IT",
    coords: [9.405, 45.53],
    milk: "Cow",
    texture: "Creamy & blue",
    description:
      "Choose dolce for a spoonably soft introduction or piccante for a bolder finish. Both make a compelling case for one more slice of bread.",
    bread: "Rosemary focaccia",
    wine: "Passito",
    tea: "Keemun black tea",
    coffee: "Chocolate-toned espresso",
    label: [18, -11],
  },
  {
    id: "parmigiano",
    name: "Parmigiano Reggiano",
    place: "Parma, Emilia-Romagna",
    country: "Italy",
    code: "IT",
    coords: [10.328, 44.801],
    milk: "Cow",
    texture: "Hard & crystalline",
    description:
      "Break off a small piece and give it a moment. There are toasted nuts, broth, and a sweetness that only time can bring. This is a cheese worth travelling for.",
    bread: "Grissini",
    wine: "Lambrusco",
    tea: "Hojicha",
    coffee: "Espresso",
    source: "https://www.parmigianoreggiano.com/en-US/dairies-visit-tasting",
    visitNote:
      "This pin marks Parma. Select and book a specific dairy through the official consortium before navigating.",
  },
  {
    id: "pecorino",
    name: "Pecorino Toscano",
    place: "Pienza, Tuscany",
    country: "Italy",
    code: "IT",
    coords: [11.678, 43.077],
    milk: "Sheep",
    texture: "Firm & mellow",
    description:
      "An excuse to take the scenic road through the Val d’Orcia. Taste a young pecorino beside an aged one, with Tuscan bread and an unhurried evening.",
    bread: "Tuscan bread",
    wine: "Sangiovese",
    tea: "Oolong",
    coffee: "Medium-roast espresso",
    label: [14, 17],
  },
  {
    id: "mozzarella",
    name: "Mozzarella di Bufala",
    place: "Caserta, Campania",
    country: "Italy",
    code: "IT",
    coords: [14.334, 41.075],
    milk: "Buffalo",
    texture: "Fresh & milky",
    description:
      "Freshness is the whole point. Seek out a local caseificio, tear the mozzarella by hand, and enjoy its sweet, milky centre with almost nothing else.",
    bread: "Plain sourdough",
    wine: "Falanghina",
    tea: "White tea",
    coffee: "Light, chilled filter coffee",
  },
  {
    id: "roquefort",
    name: "Roquefort",
    place: "Roquefort-sur-Soulzon, Aveyron",
    country: "France",
    code: "FR",
    coords: [2.989, 43.976],
    milk: "Sheep",
    texture: "Bold & blue",
    description:
      "Cool limestone caves and a cheese with unmistakable character. Its salty, tangy richness loves a little sweetness alongside.",
    bread: "Raisin & walnut bread",
    wine: "Sauternes",
    tea: "Keemun black tea",
    coffee: "Chocolate-toned espresso",
    venue: "Caves Roquefort Société",
    source: "https://www.roquefort-societe.com/les-caves/",
    visitNote:
      "The venue does not allow campervans or large vehicles in its car park. Arrange other parking before visiting.",
    label: [-90, 17],
  },
  {
    id: "cabrales",
    name: "Cabrales",
    place: "Arenas de Cabrales, Asturias",
    country: "Spain",
    code: "ES",
    coords: [-4.817, 43.303],
    milk: "Mixed",
    texture: "Intense & blue",
    description:
      "A wonderfully assertive blue from the green north of Spain. Mountain air, a little bread, and a small glass of cider make fine companions.",
    bread: "Rustic wheat bread",
    wine: "Asturian cider",
    tea: "Smoky black tea",
    coffee: "Dark-roast espresso",
    label: [-24, -19],
  },
  {
    id: "manchego",
    name: "Manchego",
    place: "Almagro, La Mancha",
    country: "Spain",
    code: "ES",
    coords: [-3.712, 38.889],
    milk: "Sheep",
    texture: "Firm & buttery",
    description:
      "Under the wide skies of La Mancha, sheep’s milk becomes something both rich and beautifully balanced. Try thin wedges with crisp bread.",
    bread: "Picos crackers",
    wine: "Tempranillo",
    tea: "Roasted oolong",
    coffee: "Nutty medium roast",
    label: [17, 8],
  },
  {
    id: "mahon",
    name: "Mahón-Menorca",
    place: "Maó, Menorca",
    country: "Spain",
    code: "ES",
    coords: [4.265, 39.889],
    milk: "Cow",
    texture: "Firm & tangy",
    description:
      "A little island detour for a sun-coloured cheese. Young Mahón is gentle and tangy; older wheels bring spice and a longer finish.",
    bread: "Olive-oil crackers",
    wine: "Dry white wine",
    tea: "Green tea",
    coffee: "Gentle cold brew",
    visitNote:
      "Menorca requires a ferry or flight. Map connections do not represent driveable roads.",
  },
  {
    id: "serra",
    name: "Serra da Estrela",
    place: "Celorico da Beira",
    country: "Portugal",
    code: "PT",
    coords: [-7.391, 40.635],
    milk: "Sheep",
    texture: "Soft & spoonable",
    description:
      "A generous, flowing centre beneath an unassuming rind. This is a cheese for sharing, with sturdy bread and a table that nobody wants to leave.",
    bread: "Portuguese country bread",
    wine: "Dão white",
    tea: "White peony tea",
    coffee: "Mellow filter coffee",
  },
  {
    id: "azeitao",
    name: "Azeitão",
    place: "Azeitão, Setúbal",
    country: "Portugal",
    code: "PT",
    coords: [-9.01, 38.52],
    milk: "Sheep",
    texture: "Soft & tangy",
    description:
      "Small in size, generous in flavour. The hills south of Lisbon offer a soft sheep’s cheese with a bright, pleasantly rustic character.",
    bread: "Crusty wheat bread",
    wine: "Setúbal Moscatel",
    tea: "Darjeeling",
    coffee: "Light-roast filter coffee",
  },
  {
    id: "feta",
    name: "Feta",
    place: "Ioannina, Epirus",
    country: "Greece",
    code: "GR",
    coords: [20.853, 39.665],
    milk: "Sheep & goat",
    texture: "Brined & crumbly",
    description:
      "Taste feta on its own and discover more than its familiar saltiness. Epirus is one starting point for exploring this cheese’s many Greek regional expressions.",
    bread: "Barley rusks",
    wine: "Assyrtiko",
    tea: "Greek mountain tea",
    coffee: "Greek coffee",
  },
  {
    id: "graviera",
    name: "Graviera Kritis",
    place: "Rethymno, Crete",
    country: "Greece",
    code: "GR",
    coords: [24.475, 35.366],
    milk: "Sheep & goat",
    texture: "Firm & sweet",
    description:
      "A Cretan mountain cheese with a gentle sweetness and a satisfying depth. Pair it with a barley rusk, then find a spot facing the sea.",
    bread: "Cretan barley rusks",
    wine: "Vidiano",
    tea: "Greek mountain tea",
    coffee: "Greek coffee",
    visitNote:
      "Crete requires a ferry or flight. This pin is a regional starting point.",
  },
];

export const trails = [
  {
    id: "alpine",
    name: "The Alpine passage",
    subtitle: "From the Jura to the Italian foothills",
    eyebrow: "MOUNTAINS & MEADOWS",
    image: "/images/alpine-lake.jpg",
    ids: [
      "comte",
      "emmental",
      "gruyere",
      "reblochon",
      "gorgonzola",
      "parmigiano",
    ],
  },
  {
    id: "france",
    name: "La vie en fromage",
    subtitle: "A leisurely ramble through France",
    eyebrow: "THE FRENCH COUNTRYSIDE",
    image: "/images/lavender.jpg",
    ids: ["camembert", "brie", "comte", "reblochon", "roquefort"],
  },
  {
    id: "italy",
    name: "A taste of la dolce vita",
    subtitle: "Good cheese. Beautifully long lunches.",
    eyebrow: "THE ITALIAN TABLE",
    image: "/images/italy.jpg",
    ids: ["gorgonzola", "parmigiano", "pecorino", "mozzarella"],
  },
];
export const countries = [...new Set(stops.map((s) => s.country))].sort();
export const defaultRoute = trails[0].ids;
export const getStop = (id: string) => stops.find((s) => s.id === id);
